#pragma once

// СГЕНЕРИРОВАНО Scripts/gen_viewmodel_table.py — правки затрутся.
// Пути статические намеренно: перебирать реестр ассетов в рантайме нельзя,
// в собранной игре пересканирование пути стирает записи из кука.

static const FRSVMEntry GVMTable[] =
{
	{ ERSWeapon::Glock,
		TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18.v_pist_glock18"),
		TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_glock_idle.v_pist_glock18_glock_idle"),
		TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_glock_draw.v_pist_glock18_glock_draw"),
		TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_glock_reload.v_pist_glock18_glock_reload"),
		{ TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_glock_firelast.v_pist_glock18_glock_firelast"),
		  TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_glock_firesingle.v_pist_glock18_glock_firesingle"),
		  nullptr },
		TEXT("/Game/Weapons/VM/v_pist_glock18/v_pist_glock18/SkeletalMeshes/v_pist_glock18_lookat01.v_pist_glock18_lookat01") },
	{ ERSWeapon::USP,
		TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_usp.v_pist_usp"),
		TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_uspidle_masked_flash.v_pist_uspidle_masked_flash"),
		TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_usp_draw.v_pist_usp_draw"),
		TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_uspreload_masked_flash.v_pist_uspreload_masked_flash"),
		{ TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_uspshoot1_masked_flash.v_pist_uspshoot1_masked_flash"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_pist_usp/v_pist_usp/SkeletalMeshes/v_pist_usplookat01_masked_flash.v_pist_usplookat01_masked_flash") },
	{ ERSWeapon::P250,
		TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250.v_pist_p250"),
		TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_idle.v_pist_p250_idle"),
		TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_draw.v_pist_p250_draw"),
		TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_reload.v_pist_p250_reload"),
		{ TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_shoot1.v_pist_p250_shoot1"),
		  TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_shoot2.v_pist_p250_shoot2"),
		  TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_shoot3.v_pist_p250_shoot3") },
		TEXT("/Game/Weapons/VM/v_pist_p250/v_pist_p250/SkeletalMeshes/v_pist_p250_lookat01.v_pist_p250_lookat01") },
	{ ERSWeapon::Deagle,
		TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle.v_pist_deagle"),
		TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_idle1.v_pist_deagle_idle1"),
		TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_draw.v_pist_deagle_draw"),
		TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_reload.v_pist_deagle_reload"),
		{ TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_shoot1.v_pist_deagle_shoot1"),
		  TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_shoot2.v_pist_deagle_shoot2"),
		  TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_shoot3.v_pist_deagle_shoot3") },
		TEXT("/Game/Weapons/VM/v_pist_deagle/v_pist_deagle/SkeletalMeshes/v_pist_deagle_lookat01.v_pist_deagle_lookat01") },
	{ ERSWeapon::FiveSeven,
		TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven.v_pist_fiveseven"),
		TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven_idle.v_pist_fiveseven_idle"),
		TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven_draw.v_pist_fiveseven_draw"),
		TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven_reload.v_pist_fiveseven_reload"),
		{ TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven_shoot1.v_pist_fiveseven_shoot1"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_pist_fiveseven/v_pist_fiveseven/SkeletalMeshes/v_pist_fiveseven_lookat01.v_pist_fiveseven_lookat01") },
	{ ERSWeapon::MP9,
		TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9.v_smg_mp9"),
		TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_idle1.v_smg_mp9_idle1"),
		TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_draw.v_smg_mp9_draw"),
		TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_reload.v_smg_mp9_reload"),
		{ TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_fire1.v_smg_mp9_fire1"),
		  TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_fire2.v_smg_mp9_fire2"),
		  TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_fire3.v_smg_mp9_fire3") },
		TEXT("/Game/Weapons/VM/v_smg_mp9/v_smg_mp9/SkeletalMeshes/v_smg_mp9_lookat01.v_smg_mp9_lookat01") },
	{ ERSWeapon::MAC10,
		TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10.v_smg_mac10"),
		TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_idle.v_smg_mac10_mac10_idle"),
		TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_draw.v_smg_mac10_mac10_draw"),
		TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_reload.v_smg_mac10_mac10_reload"),
		{ TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_fire.v_smg_mac10_mac10_fire"),
		  TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_fire2.v_smg_mac10_mac10_fire2"),
		  TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_mac10_fire3.v_smg_mac10_mac10_fire3") },
		TEXT("/Game/Weapons/VM/v_smg_mac10/v_smg_mac10/SkeletalMeshes/v_smg_mac10_lookat01.v_smg_mac10_lookat01") },
	{ ERSWeapon::UMP45,
		TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45.v_smg_ump45"),
		TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_idle1.v_smg_ump45_idle1"),
		TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_draw.v_smg_ump45_draw"),
		TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_reload.v_smg_ump45_reload"),
		{ TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_shoot1.v_smg_ump45_shoot1"),
		  TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_shoot2.v_smg_ump45_shoot2"),
		  TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_shoot3.v_smg_ump45_shoot3") },
		TEXT("/Game/Weapons/VM/v_smg_ump45/v_smg_ump45/SkeletalMeshes/v_smg_ump45_lookat01.v_smg_ump45_lookat01") },
	{ ERSWeapon::P90,
		TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90.v_smg_p90"),
		TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90a_idle.v_smg_p90a_idle"),
		TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90_draw.v_smg_p90_draw"),
		TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90a_reload.v_smg_p90a_reload"),
		{ TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90_shoot1.v_smg_p90_shoot1"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_smg_p90/v_smg_p90/SkeletalMeshes/v_smg_p90_lookat01.v_smg_p90_lookat01") },
	{ ERSWeapon::Nova,
		TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova.v_shot_nova"),
		TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova_idle.v_shot_nova_idle"),
		TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova_draw.v_shot_nova_draw"),
		TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova_after_reload.v_shot_nova_after_reload"),
		{ TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova_shoot1.v_shot_nova_shoot1"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_shot_nova/v_shot_nova/SkeletalMeshes/v_shot_nova_lookat01.v_shot_nova_lookat01") },
	{ ERSWeapon::XM1014,
		TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014.v_shot_xm1014"),
		TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014_idle.v_shot_xm1014_idle"),
		TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014_draw.v_shot_xm1014_draw"),
		TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014_after_reload.v_shot_xm1014_after_reload"),
		{ TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014_shoot1.v_shot_xm1014_shoot1"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_shot_xm1014/v_shot_xm1014/SkeletalMeshes/v_shot_xm1014_lookat01.v_shot_xm1014_lookat01") },
	{ ERSWeapon::GalilAR,
		TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar.v_rif_galilar"),
		TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_idle.v_rif_galilar_idle"),
		TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_draw.v_rif_galilar_draw"),
		TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_reload.v_rif_galilar_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_shoot1.v_rif_galilar_shoot1"),
		  TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_shoot2.v_rif_galilar_shoot2"),
		  TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_shoot3.v_rif_galilar_shoot3") },
		TEXT("/Game/Weapons/VM/v_rif_galilar/v_rif_galilar/SkeletalMeshes/v_rif_galilar_lookat01.v_rif_galilar_lookat01") },
	{ ERSWeapon::FAMAS,
		TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas.v_rif_famas"),
		TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_idle.v_rif_famas_idle"),
		TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_draw.v_rif_famas_draw"),
		TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_reload.v_rif_famas_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_shoot1.v_rif_famas_shoot1"),
		  TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_shoot2.v_rif_famas_shoot2"),
		  TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_shoot3.v_rif_famas_shoot3") },
		TEXT("/Game/Weapons/VM/v_rif_famas/v_rif_famas/SkeletalMeshes/v_rif_famas_lookat01.v_rif_famas_lookat01") },
	{ ERSWeapon::AK47,
		TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47.v_rif_ak47"),
		TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_idle.v_rif_ak47_ak47_idle"),
		TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_draw.v_rif_ak47_ak47_draw"),
		TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_reload.v_rif_ak47_ak47_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_fire1.v_rif_ak47_ak47_fire1"),
		  TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_fire2.v_rif_ak47_ak47_fire2"),
		  TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_ak47_fire3.v_rif_ak47_ak47_fire3") },
		TEXT("/Game/Weapons/VM/v_rif_ak47/v_rif_ak47/SkeletalMeshes/v_rif_ak47_lookat01.v_rif_ak47_lookat01") },
	{ ERSWeapon::M4A4,
		TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4.v_rif_m4a4"),
		TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_idle.v_rif_m4a4_idle"),
		TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_draw.v_rif_m4a4_draw"),
		TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_reload.v_rif_m4a4_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_shoot1.v_rif_m4a4_shoot1"),
		  TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_shoot2.v_rif_m4a4_shoot2"),
		  TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_shoot3.v_rif_m4a4_shoot3") },
		TEXT("/Game/Weapons/VM/v_rif_m4a4/v_rif_m4a4/SkeletalMeshes/v_rif_m4a4_lookat01.v_rif_m4a4_lookat01") },
	{ ERSWeapon::AUG,
		TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug.v_rif_aug"),
		TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_idle.v_rif_aug_idle"),
		TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_draw.v_rif_aug_draw"),
		TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_reload.v_rif_aug_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_ironsight_fire.v_rif_aug_ironsight_fire"),
		  TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_shoot1.v_rif_aug_shoot1"),
		  nullptr },
		TEXT("/Game/Weapons/VM/v_rif_aug/v_rif_aug/SkeletalMeshes/v_rif_aug_lookat01.v_rif_aug_lookat01") },
	{ ERSWeapon::SG553,
		TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556.v_rif_sg556"),
		TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_idle.v_rif_sg556_idle"),
		TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_draw.v_rif_sg556_draw"),
		TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_reload.v_rif_sg556_reload"),
		{ TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_ironsight_fire.v_rif_sg556_ironsight_fire"),
		  TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_shoot1.v_rif_sg556_shoot1"),
		  nullptr },
		TEXT("/Game/Weapons/VM/v_rif_sg556/v_rif_sg556/SkeletalMeshes/v_rif_sg556_lookat01.v_rif_sg556_lookat01") },
	{ ERSWeapon::SSG08,
		TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08.v_snip_ssg08"),
		TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08_idle1.v_snip_ssg08_idle1"),
		TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08_draw.v_snip_ssg08_draw"),
		TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08_reload.v_snip_ssg08_reload"),
		{ TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08_shoot.v_snip_ssg08_shoot"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_snip_ssg08/v_snip_ssg08/SkeletalMeshes/v_snip_ssg08_lookat01.v_snip_ssg08_lookat01") },
	{ ERSWeapon::AWP,
		TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp.v_snip_awp"),
		TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp_awp_idle.v_snip_awp_awp_idle"),
		TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp_awp_draw.v_snip_awp_awp_draw"),
		TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp_awp_reload.v_snip_awp_awp_reload"),
		{ TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp_awp_fire.v_snip_awp_awp_fire"),
		  nullptr,
		  nullptr },
		TEXT("/Game/Weapons/VM/v_snip_awp/v_snip_awp/SkeletalMeshes/v_snip_awp_lookat01.v_snip_awp_lookat01") },
	{ ERSWeapon::HEGrenade,
		TEXT("/Game/Weapons/VM/v_eq_fraggrenade/v_eq_fraggrenade/SkeletalMeshes/v_eq_fraggrenade.v_eq_fraggrenade"),
		TEXT("/Game/Weapons/VM/v_eq_fraggrenade/v_eq_fraggrenade/SkeletalMeshes/v_eq_fraggrenade_idle.v_eq_fraggrenade_idle"),
		TEXT("/Game/Weapons/VM/v_eq_fraggrenade/v_eq_fraggrenade/SkeletalMeshes/v_eq_fraggrenade_deploy.v_eq_fraggrenade_deploy"),
		nullptr,
		{ TEXT("/Game/Weapons/VM/v_eq_fraggrenade/v_eq_fraggrenade/SkeletalMeshes/v_eq_fraggrenade_throw.v_eq_fraggrenade_throw"),
		  nullptr,
		  nullptr },
		nullptr },
	{ ERSWeapon::Flashbang,
		TEXT("/Game/Weapons/VM/v_eq_flashbang/v_eq_flashbang/SkeletalMeshes/v_eq_flashbang.v_eq_flashbang"),
		TEXT("/Game/Weapons/VM/v_eq_flashbang/v_eq_flashbang/SkeletalMeshes/v_eq_flashbang_idle.v_eq_flashbang_idle"),
		TEXT("/Game/Weapons/VM/v_eq_flashbang/v_eq_flashbang/SkeletalMeshes/v_eq_flashbang_deploy.v_eq_flashbang_deploy"),
		nullptr,
		{ TEXT("/Game/Weapons/VM/v_eq_flashbang/v_eq_flashbang/SkeletalMeshes/v_eq_flashbang_throw.v_eq_flashbang_throw"),
		  nullptr,
		  nullptr },
		nullptr },
	{ ERSWeapon::SmokeGrenade,
		TEXT("/Game/Weapons/VM/v_eq_smokegrenade/v_eq_smokegrenade/SkeletalMeshes/v_eq_smokegrenade.v_eq_smokegrenade"),
		TEXT("/Game/Weapons/VM/v_eq_smokegrenade/v_eq_smokegrenade/SkeletalMeshes/v_eq_smokegrenade_idle.v_eq_smokegrenade_idle"),
		TEXT("/Game/Weapons/VM/v_eq_smokegrenade/v_eq_smokegrenade/SkeletalMeshes/v_eq_smokegrenade_deploy.v_eq_smokegrenade_deploy"),
		nullptr,
		{ TEXT("/Game/Weapons/VM/v_eq_smokegrenade/v_eq_smokegrenade/SkeletalMeshes/v_eq_smokegrenade_throw.v_eq_smokegrenade_throw"),
		  nullptr,
		  nullptr },
		nullptr },
};
